[[presetRooms]]
name = "room_entry"
width = 208
height = 144
walls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ -1, -1,], [ 1, -1,], [ 2, -1,], [ 4, -1,], [ 5, -1,], [ 13, -1,], [ -1, 0,], [ 13, 0,], [ -1, 1,], [ 13, 1,], [ 13, 2,], [ 9, 3,], [ 10, 3,], [ 13, 3,], [ -1, 4,], [ 9, 4,], [ 10, 4,], [ 13, 4,], [ -1, 5,], [ -1, 6,], [ 13, 6,], [ -1, 7,], [ 2, 7,], [ 3, 7,], [ 4, 7,], [ 13, 7,], [ -1, 8,], [ 2, 8,], [ 3, 8,], [ 4, 8,], [ 13, 8,], [ -1, 9,], [ 0, 9,], [ 1, 9,], [ 2, 9,], [ 3, 9,], [ 4, 9,], [ 5, 9,], [ 6, 9,], [ 8, 9,], [ 9, 9,], [ 10, 9,], [ 11, 9,], [ 12, 9,], [ 13, 9,],]
[[presetRooms.assets]]
name = "WallShelf"
relativeX = 128
relativeY = -32

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 64
relativeY = -32

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 16
relativeY = -32

[[presetRooms.assets]]
name = "DoorHorizontal"
relativeX = 0
relativeY = 16

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 144
relativeY = 48

[[presetRooms.assets]]
name = "DoorVertical"
relativeX = 192
relativeY = 64

[[presetRooms.assets]]
name = "Dressing"
relativeX = 32
relativeY = 112

[[presetRooms.assets]]
name = "DoorVertical"
relativeX = 96
relativeY = 112




[[presetRooms]]
name = "room_bedroom"
width = 240
height = 128
walls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ 14, -2,], [ -1, -1,], [ 1, -1,], [ 2, -1,], [ 3, -1,], [ 4, -1,], [ 6, -1,], [ 7, -1,], [ 10, -1,], [ 11, -1,], [ 12, -1,], [ 13, -1,], [ 14, -1,], [ -1, 0,], [ 13, 0,], [ 14, 0,], [ -1, 1,], [ 13, 1,], [ 14, 1,], [ 13, 2,], [ 14, 2,], [ 13, 3,], [ 14, 3,], [ -1, 4,], [ 13, 4,], [ 14, 4,], [ -1, 5,], [ 1, 5,], [ 2, 5,], [ 4, 5,], [ 5, 5,], [ 13, 5,], [ 14, 5,], [ -1, 6,], [ 1, 6,], [ 2, 6,], [ 4, 6,], [ 5, 6,], [ 6, 6,], [ 7, 6,], [ 8, 6,], [ 13, 6,], [ 14, 6,], [ -1, 7,], [ 1, 7,], [ 2, 7,], [ 4, 7,], [ 5, 7,], [ 6, 7,], [ 7, 7,], [ 8, 7,], [ 13, 7,], [ 14, 7,], [ -1, 8,], [ 0, 8,], [ 1, 8,], [ 2, 8,], [ 3, 8,], [ 4, 8,], [ 5, 8,], [ 6, 8,], [ 7, 8,], [ 8, 8,], [ 9, 8,], [ 10, 8,], [ 12, 8,], [ 13, 8,], [ 14, 8,],]
[[presetRooms.assets]]
name = "WallShelf"
relativeX = 144
relativeY = -32

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 192
relativeY = -32

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 96
relativeY = -32

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 16
relativeY = -32

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 48
relativeY = -32

[[presetRooms.assets]]
name = "Dressing"
relativeX = 160
relativeY = -16

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = -16

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = 16

[[presetRooms.assets]]
name = "DoorHorizontal"
relativeX = 0
relativeY = 16

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = 48

[[presetRooms.assets]]
name = "ClosetBack"
relativeX = 64
relativeY = 80

[[presetRooms.assets]]
name = "ClosetBack"
relativeX = 16
relativeY = 80

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = 80

[[presetRooms.assets]]
name = "DoorVertical"
relativeX = 160
relativeY = 96

[[presetRooms.assets]]
name = "Dressing"
relativeX = 96
relativeY = 96

[[presetRooms]]
name = "room_TVRoom"
width = 240
height = 80
walls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ 14, -2,], [ 15, -2,], [ -1, -1,], [ 15, -1,], [ -1, 0,], [ -1, 1,], [ 2, 1,], [ 3, 1,], [ 4, 1,], [ 6, 1,], [ 7, 1,], [ 8, 1,], [ 10, 1,], [ 11, 1,], [ 12, 1,], [ -1, 2,], [ 15, 2,], [ 15, 3,], [ 15, 4,], [ -1, 5,], [ 0, 5,], [ 1, 5,], [ 2, 5,], [ 3, 5,], [ 4, 5,], [ 5, 5,], [ 6, 5,], [ 7, 5,], [ 8, 5,], [ 9, 5,], [ 10, 5,], [ 11, 5,], [ 12, 5,], [ 13, 5,], [ 14, 5,], [ 15, 5,],]
[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 32
relativeY = -32

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 80
relativeY = -32

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 128
relativeY = -32

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 176
relativeY = -32

[[presetRooms.assets]]
name = "DoorHorizontal"
relativeX = 224
relativeY = -16

[[presetRooms.assets]]
name = "CouchFront"
relativeX = 32
relativeY = 16

[[presetRooms.assets]]
name = "CouchFront"
relativeX = 96
relativeY = 16

[[presetRooms.assets]]
name = "CouchFront"
relativeX = 160
relativeY = 16

[[presetRooms.assets]]
name = "DoorHorizontal"
relativeX = 0
relativeY = 32


[[presetRooms]]
name = "room_livingRoom"
width = 208
height = 176
walls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ -1, -1,], [ 13, -1,], [ 13, 0,], [ 2, 1,], [ 3, 1,], [ 4, 1,], [ 5, 1,], [ 6, 1,], [ 7, 1,], [ 13, 1,], [ -1, 2,], [ 13, 2,], [ -1, 3,], [ 10, 3,], [ 11, 3,], [ 13, 3,], [ -1, 4,], [ 2, 4,], [ 3, 4,], [ 6, 4,], [ 7, 4,], [ 10, 4,], [ 11, 4,], [ 13, 4,], [ -1, 5,], [ 2, 5,], [ 3, 5,], [ 6, 5,], [ 7, 5,], [ 10, 5,], [ 11, 5,], [ 13, 5,], [ -1, 6,], [ 2, 6,], [ 3, 6,], [ 4, 6,], [ 5, 6,], [ 6, 6,], [ 7, 6,], [ 10, 6,], [ 11, 6,], [ 13, 6,], [ -1, 7,], [ 10, 7,], [ 11, 7,], [ 13, 7,], [ -1, 8,], [ 10, 8,], [ 11, 8,], [ 13, 8,], [ -1, 9,], [ 13, 9,], [ -1, 10,], [ 13, 10,], [ -1, 11,], [ 0, 11,], [ 1, 11,], [ 2, 11,], [ 3, 11,], [ 4, 11,], [ 5, 11,], [ 8, 11,], [ 9, 11,], [ 10, 11,], [ 11, 11,], [ 12, 11,], [ 13, 11,],]
[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 32
relativeY = -32

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 96
relativeY = -32

[[presetRooms.assets]]
name = "DoorHorizontal"
relativeX = 0
relativeY = -16

[[presetRooms.assets]]
name = "CouchFront"
relativeX = 32
relativeY = 16

[[presetRooms.assets]]
name = "CouchFront"
relativeX = 80
relativeY = 16

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 160
relativeY = 48

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 32
relativeY = 64

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 96
relativeY = 64

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 160
relativeY = 80

[[presetRooms.assets]]
name = "TableHorizontal"
relativeX = 32
relativeY = 96

[[presetRooms.assets]]
name = "TableHorizontal"
relativeX = 80
relativeY = 96

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 160
relativeY = 112

[[presetRooms.assets]]
name = "DoorHorizontal"
relativeX = 128
relativeY = 144

