[[presetRooms]]
name = "room_entry"
width = 208
height = 144
[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 16
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 64
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "WallShelf"
relativeX = 160
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "TableHorizontal"
relativeX = 160
relativeY = -8
reversed = false

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 144
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 176
relativeY = 64
reversed = false

[[presetRooms.assets]]
name = "Dressing"
relativeX = 32
relativeY = 112
reversed = false


[presetRooms.walls]
highWalls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ -1, -1,], [ 13, -1,], [ -1, 0,], [ 13, 0,], [ -1, 1,], [ 13, 1,], [ -1, 2,], [ 13, 2,], [ -1, 3,], [ 13, 3,], [ -1, 4,], [ 13, 4,], [ -1, 5,], [ 13, 5,], [ -1, 6,], [ 13, 6,], [ -1, 7,], [ 13, 7,], [ -1, 8,], [ 13, 8,], [ -1, 9,], [ 0, 9,], [ 1, 9,], [ 2, 9,], [ 3, 9,], [ 4, 9,], [ 5, 9,], [ 6, 9,], [ 7, 9,], [ 8, 9,], [ 9, 9,], [ 10, 9,], [ 11, 9,], [ 12, 9,], [ 13, 9,],]
lowWalls = [ [ 1, -1,], [ 2, -1,], [ 4, -1,], [ 5, -1,], [ 10, -1,], [ 11, -1,], [ 12, -1,], [ 10, 0,], [ 11, 0,], [ 12, 0,], [ 9, 3,], [ 10, 3,], [ 9, 4,], [ 10, 4,], [ 2, 7,], [ 3, 7,], [ 4, 7,], [ 2, 8,], [ 3, 8,], [ 4, 8,],]
[presetRooms.exitsPos]
up = [ 7, 0,]
down = [ 7, 8,]
left = [ 0, 2,]
right = [ 12, 5,]
[[presetRooms]]
name = "room_bedroom"
width = 240
height = 128
[[presetRooms.assets]]
name = "WallShelf"
relativeX = 192
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 48
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 16
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 96
relativeY = -32
reversed = true

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = 16
reversed = true

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 208
relativeY = 80
reversed = true

[[presetRooms.assets]]
name = "ClosetBack"
relativeX = 16
relativeY = 80
reversed = false

[[presetRooms.assets]]
name = "ClosetBack"
relativeX = 64
relativeY = 80
reversed = false

[[presetRooms.assets]]
name = "Dressing"
relativeX = 96
relativeY = 96
reversed = false


[presetRooms.walls]
highWalls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ 14, -2,], [ 15, -2,], [ -1, -1,], [ 15, -1,], [ -1, 0,], [ 15, 0,], [ -1, 1,], [ 15, 1,], [ -1, 2,], [ 15, 2,], [ -1, 3,], [ 15, 3,], [ -1, 4,], [ 15, 4,], [ -1, 5,], [ 15, 5,], [ -1, 6,], [ 15, 6,], [ -1, 7,], [ 15, 7,], [ -1, 8,], [ 0, 8,], [ 1, 8,], [ 2, 8,], [ 3, 8,], [ 4, 8,], [ 5, 8,], [ 6, 8,], [ 7, 8,], [ 8, 8,], [ 9, 8,], [ 10, 8,], [ 11, 8,], [ 12, 8,], [ 13, 8,], [ 14, 8,],]
lowWalls = [ [ 1, -1,], [ 2, -1,], [ 3, -1,], [ 4, -1,], [ 6, -1,], [ 7, -1,], [ 10, -1,], [ 11, -1,], [ 12, -1,], [ 13, -1,], [ 14, -1,], [ 13, 0,], [ 14, 0,], [ 13, 1,], [ 14, 1,], [ 13, 2,], [ 14, 2,], [ 13, 3,], [ 14, 3,], [ 13, 4,], [ 14, 4,], [ 1, 5,], [ 2, 5,], [ 4, 5,], [ 5, 5,], [ 13, 5,], [ 14, 5,], [ 1, 6,], [ 2, 6,], [ 4, 6,], [ 5, 6,], [ 6, 6,], [ 7, 6,], [ 8, 6,], [ 13, 6,], [ 14, 6,], [ 1, 7,], [ 2, 7,], [ 4, 7,], [ 5, 7,], [ 6, 7,], [ 7, 7,], [ 8, 7,], [ 13, 7,], [ 14, 7,],]
[presetRooms.exitsPos]
up = [ 9, 0,]
down = [ 10, 7,]
left = [ 0, 2,]
right = []
[[presetRooms]]
name = "room_TVRoom"
width = 240
height = 80
[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 176
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 128
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 80
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 32
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "CouchBack"
relativeX = 160
relativeY = 16
reversed = false

[[presetRooms.assets]]
name = "CouchBack"
relativeX = 96
relativeY = 16
reversed = false

[[presetRooms.assets]]
name = "CouchBack"
relativeX = 32
relativeY = 16
reversed = false


[presetRooms.walls]
highWalls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ 14, -2,], [ 15, -2,], [ -1, -1,], [ 15, -1,], [ -1, 0,], [ 15, 0,], [ -1, 1,], [ 15, 1,], [ -1, 2,], [ 15, 2,], [ -1, 3,], [ 15, 3,], [ -1, 4,], [ 15, 4,], [ -1, 5,], [ 0, 5,], [ 1, 5,], [ 2, 5,], [ 3, 5,], [ 4, 5,], [ 5, 5,], [ 6, 5,], [ 7, 5,], [ 8, 5,], [ 9, 5,], [ 10, 5,], [ 11, 5,], [ 12, 5,], [ 13, 5,], [ 14, 5,], [ 15, 5,],]
lowWalls = [ [ 2, 1,], [ 3, 1,], [ 4, 1,], [ 6, 1,], [ 7, 1,], [ 8, 1,], [ 10, 1,], [ 11, 1,], [ 12, 1,],]
[presetRooms.exitsPos]
up = []
down = [ 6, 4,]
left = [ 0, 2,]
right = [ 14, 1,]
[[presetRooms]]
name = "room_livingRoom"
width = 208
height = 176
[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 96
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "WallTelevision"
relativeX = 32
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "CouchFront"
relativeX = 80
relativeY = 16
reversed = false

[[presetRooms.assets]]
name = "CouchFront"
relativeX = 32
relativeY = 16
reversed = false

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 160
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 96
relativeY = 64
reversed = false

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 32
relativeY = 64
reversed = false

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 160
relativeY = 80
reversed = false

[[presetRooms.assets]]
name = "TableHorizontal"
relativeX = 80
relativeY = 96
reversed = false

[[presetRooms.assets]]
name = "TableHorizontal"
relativeX = 32
relativeY = 96
reversed = false

[[presetRooms.assets]]
name = "BedVertical"
relativeX = 160
relativeY = 112
reversed = false


[presetRooms.walls]
highWalls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ -1, -1,], [ 13, -1,], [ -1, 0,], [ 13, 0,], [ -1, 1,], [ 13, 1,], [ -1, 2,], [ 13, 2,], [ -1, 3,], [ 13, 3,], [ -1, 4,], [ 13, 4,], [ -1, 5,], [ 13, 5,], [ -1, 6,], [ 13, 6,], [ -1, 7,], [ 13, 7,], [ -1, 8,], [ 13, 8,], [ -1, 9,], [ 13, 9,], [ -1, 10,], [ 13, 10,], [ -1, 11,], [ 0, 11,], [ 1, 11,], [ 2, 11,], [ 3, 11,], [ 4, 11,], [ 5, 11,], [ 6, 11,], [ 7, 11,], [ 8, 11,], [ 9, 11,], [ 10, 11,], [ 11, 11,], [ 12, 11,], [ 13, 11,],]
lowWalls = [ [ 2, 1,], [ 3, 1,], [ 4, 1,], [ 5, 1,], [ 6, 1,], [ 7, 1,], [ 10, 3,], [ 11, 3,], [ 2, 4,], [ 3, 4,], [ 6, 4,], [ 7, 4,], [ 10, 4,], [ 11, 4,], [ 2, 5,], [ 3, 5,], [ 6, 5,], [ 7, 5,], [ 10, 5,], [ 11, 5,], [ 2, 6,], [ 3, 6,], [ 4, 6,], [ 5, 6,], [ 6, 6,], [ 7, 6,], [ 10, 6,], [ 11, 6,], [ 10, 7,], [ 11, 7,], [ 10, 8,], [ 11, 8,],]
[presetRooms.exitsPos]
up = [ 10, 0,]
down = [ 6, 10,]
left = [ 0, 1,]
right = [ 12, 1,]
[[presetRooms]]
name = "room_kitchen"
width = 144
height = 112
[[presetRooms.assets]]
name = "ShelfStorage"
relativeX = 64
relativeY = -16
reversed = true

[[presetRooms.assets]]
name = "ShelfStorage"
relativeX = 96
relativeY = -16
reversed = true

[[presetRooms.assets]]
name = "ShelfStorage"
relativeX = 80
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "ShelfStorage"
relativeX = 48
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "FridgeFront"
relativeX = 32
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "ShelfStorage"
relativeX = 112
relativeY = -16
reversed = true

[[presetRooms.assets]]
name = "WallVerticalInside"
relativeX = 128
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "CounterTopSide"
relativeX = 112
relativeY = 0
reversed = false

[[presetRooms.assets]]
name = "CounterTop"
relativeX = 96
relativeY = 0
reversed = false

[[presetRooms.assets]]
name = "CounterTop"
relativeX = 80
relativeY = 0
reversed = false

[[presetRooms.assets]]
name = "CounterTop"
relativeX = 64
relativeY = 0
reversed = false

[[presetRooms.assets]]
name = "CounterTopDrawer"
relativeX = 48
relativeY = 0
reversed = false

[[presetRooms.assets]]
name = "WallVerticalInside"
relativeX = 128
relativeY = 0
reversed = false

[[presetRooms.assets]]
name = "CounterTopSide"
relativeX = 112
relativeY = 8
reversed = false

[[presetRooms.assets]]
name = "CounterTopSide"
relativeX = 112
relativeY = 16
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 32
relativeY = 32
reversed = true

[[presetRooms.assets]]
name = "TableHorizontal"
relativeX = 48
relativeY = 32
reversed = false

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 96
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 64
relativeY = 64
reversed = true


[presetRooms.walls]
highWalls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ -1, -1,], [ 9, -1,], [ -1, 0,], [ 9, 0,], [ -1, 1,], [ 9, 1,], [ -1, 2,], [ 9, 2,], [ -1, 3,], [ 9, 3,], [ -1, 4,], [ 9, 4,], [ -1, 5,], [ 9, 5,], [ -1, 6,], [ 9, 6,], [ 0, 7,], [ 1, 7,], [ 2, 7,], [ 3, 7,], [ 4, 7,], [ 5, 7,], [ 6, 7,], [ 7, 7,], [ 8, 7,], [ 9, 7,],]
lowWalls = [ [ 2, -1,], [ 3, -1,], [ 4, -1,], [ 5, -1,], [ 6, -1,], [ 7, -1,], [ 8, -1,], [ 7, 0,], [ 8, 0,], [ 3, 2,], [ 4, 2,], [ 5, 2,],]
[presetRooms.exitsPos]
up = []
down = [ 4, 6,]
left = [ 0, 1,]
right = [ 8, 3,]
[[presetRooms]]
name = "conference_room"
width = 240
height = 224
[[presetRooms.assets]]
name = "ClosetFront"
relativeX = 160
relativeY = -32
reversed = false

[[presetRooms.assets]]
name = "FloorLamp"
relativeX = 192
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "FloorLamp"
relativeX = 48
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 112
relativeY = 16
reversed = true

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 112
relativeY = 32
reversed = false

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 80
relativeY = 32
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 64
relativeY = 32
reversed = true

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 112
relativeY = 64
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 144
relativeY = 64
reversed = false

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 80
relativeY = 64
reversed = false

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 64
relativeY = 80
reversed = true

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 112
relativeY = 96
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 64
relativeY = 96
reversed = true

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 80
relativeY = 96
reversed = false

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 144
relativeY = 112
reversed = false

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 144
relativeY = 128
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 64
relativeY = 128
reversed = true

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 96
relativeY = 144
reversed = false

[[presetRooms.assets]]
name = "ClosetBack"
relativeX = 160
relativeY = 176
reversed = false

[[presetRooms.assets]]
name = "FloorLamp"
relativeX = 192
relativeY = 192
reversed = false

[[presetRooms.assets]]
name = "FloorLamp"
relativeX = 48
relativeY = 192
reversed = false


[presetRooms.walls]
highWalls = [ [ -1, -2,], [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ 12, -2,], [ 13, -2,], [ 14, -2,], [ 15, -2,], [ -1, -1,], [ 15, -1,], [ -1, 0,], [ 15, 0,], [ -1, 1,], [ 15, 1,], [ -1, 2,], [ 15, 2,], [ -1, 3,], [ 15, 3,], [ -1, 4,], [ 15, 4,], [ -1, 5,], [ 15, 5,], [ -1, 6,], [ 15, 6,], [ -1, 7,], [ 15, 7,], [ -1, 8,], [ 15, 8,], [ -1, 9,], [ 15, 9,], [ -1, 10,], [ 15, 10,], [ -1, 11,], [ 15, 11,], [ -1, 12,], [ 15, 12,], [ -1, 13,], [ 15, 13,], [ 0, 14,], [ 1, 14,], [ 2, 14,], [ 3, 14,], [ 4, 14,], [ 5, 14,], [ 6, 14,], [ 7, 14,], [ 8, 14,], [ 9, 14,], [ 10, 14,], [ 11, 14,], [ 12, 14,], [ 13, 14,], [ 14, 14,],]
lowWalls = [ [ 3, -1,], [ 10, -1,], [ 11, -1,], [ 12, -1,], [ 5, 2,], [ 6, 2,], [ 7, 2,], [ 8, 2,], [ 5, 3,], [ 6, 3,], [ 7, 3,], [ 8, 3,], [ 5, 4,], [ 6, 4,], [ 7, 4,], [ 8, 4,], [ 5, 5,], [ 6, 5,], [ 7, 5,], [ 8, 5,], [ 5, 6,], [ 6, 6,], [ 7, 6,], [ 8, 6,], [ 5, 7,], [ 6, 7,], [ 7, 7,], [ 8, 7,], [ 10, 11,], [ 11, 11,], [ 3, 12,], [ 10, 12,], [ 11, 12,], [ 12, 12,], [ 3, 13,], [ 10, 13,], [ 11, 13,], [ 12, 13,],]
[presetRooms.exitsPos]
up = [ 1, 0,]
down = [ 6, 13,]
left = []
right = [ 14, 9,]
[[presetRooms]]
name = "wine_cave"
width = 192
height = 144
[[presetRooms.assets]]
name = "BarrelFront"
relativeX = 32
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "BarrelFront"
relativeX = 48
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "BarrelFront"
relativeX = 64
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "BarrelFront"
relativeX = 80
relativeY = -16
reversed = false

[[presetRooms.assets]]
name = "BarrelSide"
relativeX = 176
relativeY = 16
reversed = false

[[presetRooms.assets]]
name = "BarrelSide"
relativeX = 176
relativeY = 24
reversed = false

[[presetRooms.assets]]
name = "BarrelSide"
relativeX = 176
relativeY = 32
reversed = false

[[presetRooms.assets]]
name = "BarrelSide"
relativeX = 176
relativeY = 40
reversed = false

[[presetRooms.assets]]
name = "BarrelSide"
relativeX = 176
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "ChairFront"
relativeX = 96
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 32
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "TableVertical"
relativeX = 64
relativeY = 48
reversed = false

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 96
relativeY = 80
reversed = true

[[presetRooms.assets]]
name = "ChairBack"
relativeX = 32
relativeY = 96
reversed = true


[presetRooms.walls]
highWalls = [ [ 0, -2,], [ 1, -2,], [ 2, -2,], [ 3, -2,], [ 4, -2,], [ 5, -2,], [ 6, -2,], [ 7, -2,], [ 8, -2,], [ 9, -2,], [ 10, -2,], [ 11, -2,], [ -1, -1,], [ 12, -1,], [ -1, 0,], [ 12, 0,], [ -1, 1,], [ 12, 1,], [ -1, 2,], [ 12, 2,], [ -1, 3,], [ 12, 3,], [ -1, 4,], [ 12, 4,], [ -1, 5,], [ 12, 5,], [ -1, 6,], [ 12, 6,], [ -1, 7,], [ 12, 7,], [ -1, 8,], [ 12, 8,], [ 0, 9,], [ 1, 9,], [ 2, 9,], [ 3, 9,], [ 4, 9,], [ 5, 9,], [ 6, 9,], [ 7, 9,], [ 8, 9,], [ 9, 9,], [ 10, 9,], [ 11, 9,],]
lowWalls = [ [ 2, -1,], [ 3, -1,], [ 4, -1,], [ 5, -1,], [ 11, 1,], [ 11, 2,], [ 2, 3,], [ 3, 3,], [ 4, 3,], [ 5, 3,], [ 2, 4,], [ 3, 4,], [ 4, 4,], [ 5, 4,],]
[presetRooms.exitsPos]
up = [ 7, 0,]
down = [ 7, 8,]
left = [ 0, 1,]
right = [ 11, 6,]
